services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: zendesk
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: